### ISSUE TITLE
Exception while browsing the market: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by Kyria** [Pyfa-fit/Pyfa-fit#117]
## Bug Report
```
OS version: 	Windows-10-10.0.14393-SP0
Python: 	2.7.13
wxPython: 	3.0.2.0
SQLAlchemy: 	1.1.10
Logbook: 	1.0.0
pyfa version: 2017.05.21  - YC119.5 1.0
pyfa root: F:\Jeux\EVE\pyfa
save path: C:\Users\anakh\.pyfa
fs encoding: mbcs

EXCEPTION: 'ascii' codec can't encode character u'\u2018' in position 20: ordinal not in range(128)

  File "site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <lambda>
  File "gui\marketBrowser.py", line 426, in populateSearch
  File "gui\marketBrowser.py", line 375, in filterItemStore
  File "gui\display.py", line 306, in update
  File "gui\marketBrowser.py", line 468, in populate
  File "gui\marketBrowser.py", line 432, in itemSort
  File "service\market.py", line 536, in getMarketGroupByItem
```

### Detailed steps to reproduce:
Go in the market search, write "rea" 

### Release or development git branch? Please note the release version or commit hash:
Latest release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

----

looks like it's the logging that creates that issue... probably adding a `.encode('utf8')` to the `repr(item)` might do the trick

The "funnier" is that it does not happen with `re` or `reac` string...

**Comment by Ebag333** [comment]
Thanks for the report.  It's being killed by `‘Divine Harvest’ Electromagnetic Reaper` because of the unicode chars in it.

Easy enough fix

**Comment by Ebag333** [comment]
Fix released!
